name: Bug Report
description: Something does not seem right
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened that shouldn't have?
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      value: |
        1. [First step]
        2. [Second step]
        3. etc.
  - type: input
    id: insta-version
    attributes:
      label: Insta Version
      description: What version of insta are you using?
  - type: input
    id: rustc-version
    attributes:
      label: rustc Version
      description: What version of rustc are you using?
  - type: textarea
    id: expectations
    attributes:
      label: What did you expect?
      placeholder: What do you think should have happened?
