name: Check minimal version resolution

on: [push, pull_request]

jobs:
  check-minver:
    name: Test with minimal version resolution
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@cargo-minimal-versions
      - name: Test
        run: make check-minver
